version: "3.2"

services:
  neo:
    image: neo4j:3.5.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none

  api:
    build: api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/code/api/
    command: bash -c "code/api/wait-for-it.sh -t 30 -h neo -p 7474 -- python code/api/server.py"