= Cypher: Introduction to NO-SQL

== Cypher

image::https://avatars3.githubusercontent.com/u/201120[width=200,float=right]

Cypher is a graph-based query language for the Neo4J database.

Cypher can be used to write graph-based queries reminiscent of ASCII art.

A graph **G** is an ordered pair **(V**, **E)**, where stem: **V** is the set of all vertices and
**E** is the set of all edges.

== Create a node
:name: pass:a['<span value-key="name">Rüdiger</span>']

A node v of **V** can be represented by ().

This representation can be provided with the type. The operator : introduces such a type.

Here you see a node of the type person.
Each person has a name.
What name should the person have?:
++++
Person
<input style="display:inline;width:30%;" value-for="name" class="form-control" value="Rüdiger" size="40">
++++

[source, cypher,subs=attributes]
----
CREATE (a:Person {name:{name}})
RETURN a
----

== Create a node of a different type
:name: pass:a['<span value-key="name">Rüdiger</span>']
:attr: pass:a['<span value-key="name">Dog</span>']

What name and attribute should the Pet have?:
++++
Pet
<input style="display:inline;width:30%;" value-for="name" class="form-control" value="Rüdiger" size="40">
is a
<input style="display:inline;width:30%;" value-for="attr" class="form-control" value="Dog" size="40">
++++

[source, cypher,subs=attributes]
----
CREATE (a:Pet {name:{name}, type:{attr}})
RETURN a
----

== Create a between existing nodes
:name1: pass:a['<span value-key="name1">Marc</span>']
:name2: pass:a['<span value-key="name2">Rüdiger</span>']
An edge can only exist between two node.
An edge must always be directed.
The type of edge can be determined within [].

++++
<input style="display:inline;width:30%;" value-for="name1" class="form-control" value="Marc" size="40">
is a friend of
<input style="display:inline;width:30%;" value-for="name2" class="form-control" value="Rüdiger" size="40">
++++
[source, cypher,subs=attributes]
----
MATCH (a:Person{name:{name1}}),(b:Person{name:{name2}})
MERGE (a)-[r:IS_FRIEND]->(b)
RETURN a,r,b
----

== Create a between existing nodes of different type
:name: pass:a['<span value-key="name">Marc</span>']
:pet: pass:a['<span value-key="pet">Rüdiger</span>']
:type: pass:a['<span value-key="type">Dog</span>']

An edge can only exist between two node.
An edge must always be directed.
The type of edge can be determined within [].

++++
<input style="display:inline;width:30%;" value-for="name" class="form-control" value="Marc" size="40">
ownes
<input style="display:inline;width:30%;" value-for="pet" class="form-control" value="Rüdiger" size="40">
the
<input style="display:inline;width:30%;" value-for="type" class="form-control" value="Dog" size="40">
++++
[source, cypher,subs=attributes]
----
MATCH (a:Person{name:{name}}),(b:Pet{name:{pet}, type:{type}})
MERGE (a)-[r:OWNES]->(b)
RETURN a,r,b
----


== Selecting
:type: pass:a['<span value-key="name">Dog</span>']
An edge can only exist between two node.
An edge must always be directed.
The type of edge can be determined within [].

++++
<input style="display:inline;width:30%;" value-for="type" class="form-control" value="Dog" size="40">
++++

[source, cypher,subs=attributes]
----
MATCH (a:Person)-[r:OWNES]->(b:Pet{type:{type}})
RETURN a,r,b
----
